import { DefaultCategory, Language, Currency, TransactionType } from './types';

export const APP_NAME = "FlashFinance";
export const DEFAULT_TENANT = "default-tenant";

export const CURRENCY_SYMBOLS: Record<Currency, string> = {
  'BRL': 'R$',
  'USD': '$',
  'EUR': '€',
  'GBP': '£'
};

export const CATEGORY_LABELS: Record<Language, Record<string, string>> = {
  'pt-BR': {
    [DefaultCategory.FOOD]: 'Alimentação',
    [DefaultCategory.TRANSPORT]: 'Transporte',
    [DefaultCategory.HOUSING]: 'Moradia',
    [DefaultCategory.ENTERTAINMENT]: 'Lazer',
    [DefaultCategory.HEALTH]: 'Saúde',
    [DefaultCategory.SHOPPING]: 'Compras',
    [DefaultCategory.SALARY]: 'Salário',
    [DefaultCategory.INVESTMENT]: 'Investimentos',
    [DefaultCategory.FREELANCE]: 'Freelance',
    [DefaultCategory.OTHER]: 'Outros',
  },
  'en-US': {
    [DefaultCategory.FOOD]: 'Food',
    [DefaultCategory.TRANSPORT]: 'Transport',
    [DefaultCategory.HOUSING]: 'Housing',
    [DefaultCategory.ENTERTAINMENT]: 'Entertainment',
    [DefaultCategory.HEALTH]: 'Health',
    [DefaultCategory.SHOPPING]: 'Shopping',
    [DefaultCategory.SALARY]: 'Salary',
    [DefaultCategory.INVESTMENT]: 'Investments',
    [DefaultCategory.FREELANCE]: 'Freelance',
    [DefaultCategory.OTHER]: 'Other',
  }
};

export const UI_LABELS: Record<Language, any> = {
  'pt-BR': {
    // Finance
    totalMonth: 'Balanço Mensal',
    income: 'Receitas',
    expense: 'Despesas',
    quickAdd: 'Novo Registro',
    save: 'Salvar',
    cancel: 'Cancelar',
    amount: 'Valor',
    description: 'Descrição',
    category: 'Categoria',
    history: 'Histórico',
    settings: 'Configurações',
    logs: 'Logs do Sistema',
    chartTitle: 'Análise Mensal',
    emptyState: 'Nenhum registro encontrado.',
    loading: 'Carregando...',
    appearance: 'Aparência',
    languageLabel: 'Idioma',
    currencyLabel: 'Moeda',
    darkMode: 'Modo Escuro',
    lightMode: 'Modo Claro',
    manageCategories: 'Gerenciar Categorias',
    addCategory: 'Nova Categoria',
    categoryName: 'Nome da Categoria',
    delete: 'Excluir',
    filter: 'Filtrar',
    type: 'Tipo',
    customCategorySaved: 'Categoria salva!',
    customCategoryDeleted: 'Categoria removida.',
    
    // Auth & Family
    welcome: 'Bem-vindo(a)',
    selectProfile: 'Quem é você?',
    createProfile: 'Novo Perfil',
    name: 'Nome',
    pin: 'PIN (4 dígitos)',
    role: 'Papel',
    father: 'Pai',
    mother: 'Mãe',
    child: 'Filho(a)',
    login: 'Entrar',
    logout: 'Sair',
    dashboard: 'Finanças',
    family: 'Família',
    calendar: 'Calendário',
    tasks: 'Tarefas',
    dailyChecklist: 'Checklist Diário',
    addTask: 'Nova Tarefa',
    taskTitle: 'Título',
    assignedTo: 'Atribuído a',
    date: 'Data',
    enableNotifications: 'Ativar Notificações',
    notificationsEnabled: 'Notificações Ativadas'
  },
  'en-US': {
    // Finance
    totalMonth: 'Monthly Balance',
    income: 'Income',
    expense: 'Expenses',
    quickAdd: 'New Record',
    save: 'Save',
    cancel: 'Cancel',
    amount: 'Amount',
    description: 'Description',
    category: 'Category',
    history: 'History',
    settings: 'Settings',
    logs: 'System Logs',
    chartTitle: 'Monthly Analysis',
    emptyState: 'No records found.',
    loading: 'Loading...',
    appearance: 'Appearance',
    languageLabel: 'Language',
    currencyLabel: 'Currency',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    manageCategories: 'Manage Categories',
    addCategory: 'New Category',
    categoryName: 'Category Name',
    delete: 'Delete',
    filter: 'Filter',
    type: 'Type',
    customCategorySaved: 'Category saved!',
    customCategoryDeleted: 'Category deleted.',

    // Auth & Family
    welcome: 'Welcome',
    selectProfile: 'Who are you?',
    createProfile: 'New Profile',
    name: 'Name',
    pin: 'PIN (4 digits)',
    role: 'Role',
    father: 'Father',
    mother: 'Mother',
    child: 'Child',
    login: 'Login',
    logout: 'Logout',
    dashboard: 'Finance',
    family: 'Family',
    calendar: 'Calendar',
    tasks: 'Tasks',
    dailyChecklist: 'Daily Checklist',
    addTask: 'New Task',
    taskTitle: 'Title',
    assignedTo: 'Assigned To',
    date: 'Date',
    enableNotifications: 'Enable Notifications',
    notificationsEnabled: 'Notifications Enabled'
  }
};
